### ISSUE TITLE
Feature request: Support for helper functions

### ISSUE THREAD

**Issue by denniseffing** [yoichiro/vite-plugin-handlebars#12]
Currently the script only supports registering partials. It'd be awesome to support registering [custom helpers](https://handlebarsjs.com/guide/#custom-helpers) as well by providing a `helpersDirectoryPath` via the configuration.

Helper functions should work regardless of their module system, i.e. the plugin should support registering helpers written using CommonJS and ES modules.

**Comment by yoichiro** [comment]
@denniseffing Thank you for suggesting the new feature. If we could support the registration of Helper functions through a plugin, it would indeed allow for a more declarative use of Handlebars.

Registering Helper functions involves adding specific functions written in JavaScript or TypeScript to Handlebars. Since there is a high freedom in writing functions in .js or .ts files, unlike registering partials, it is not simple. I imagine it would require establishing some sort of convention.

I thought of a behavior where functions defined in .js or .ts files within the helpersDirectoryPath are automatically registered as Helper functions by the plugin. If you have any ideas on how to declare Helper functions specifically, please let me know.

**Comment by yoichiro** [comment]
@denniseffing Do you have any specific ideas? If not, I am considering closing this issue.

This plugin provides functionality to import Handlebars template files using the import syntax. In other words, currently, this plugin is intended for SPA (Single Page Application) use. Since partial files are dynamically loaded in Handlebars, this plugin handles both the loading and embedding of these files into modules. However, helper functions can be registered at any time within the SPA using the registerHelper function. Therefore, I believe there is no need for this plugin to handle the registration of helper functions.

**Comment by yoichiro** [comment]
Since I wasn't able to gather any particular feedback, I'll close this issue.

**Comment by ProfDoof** [comment]
Gonna go ahead and re-open this as this is something that I would also like. My personal suggestion would be to have this feature at a bare minimum as pulling the helpers out of the transform html index options and making them their own top-level option. Then, you can just register those functions that are passed in by hand. 

However, if you want to do something a bit more complex, you could look at something like [esbuild-plugin-handlebars](https://github.com/lighthousesystems/esbuild-plugin-handlebars) and do it like them where you can pull in the default function for a given source file. Another option would be to import all modules that are in a given directory and then iterate over the [module namespace object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import#module_namespace_object) returned by importing the modules. This would give you the functions in each and you could do a simple pass/fail if they have duplicate names or anything like that. That being said, I do think you could get away with just the first option for now and implement a more complex and complete option later. If I can find time to do so, I may even make a PR for the first option.
